### ISSUE TITLE
Cleverhans package with tensorflow incompatibility

### ISSUE THREAD

**Issue by tkangxun** [Shawn-Shan/trapdoor#2]
Hi, currently I'm trying to repeat your experiments but the cleverhans package has been giving quite a bit of problem.

When using tensorflow-gpu == 1.14,
cleverhans prompts to download 'tensorflow-addons', installing it will give an error `ImportError: cannot import name 'keras_tensor'
` instead. This is due to tensorflow-addons being only compatible with tensorflow 2.

When using tensorflow-gpu ==2.3,
the tensorflow-addons error is solved however an `AttributeError: module 'tensorflow' has no attribute 'GraphKeys'`  is surfaced within the imported cleverhans package which requires tensorflow 1. Adding a `import tensorflow.compat.v1 as tf` doesn't solve the error.

Are you able to provide the cleverhans package version that you used to run the code? Or provide another way to wrap around this error. Thank you!

**Comment by Shawn-Shan** [comment]
The code only support tensorflow-gpu==1.14. I suggest you uninstall tensorflow add-ons, since we are not using it.
